a = int(raw_input())
b = int(raw_input())
c = int(raw_input())
print pow(a,b)
print pow(a,b,c)
#Return a to the power b; if c is present, return a to the power b, modulo c (computed more efficiently than pow(a, b) % c)
